config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
    }

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'

    resources :orders, only: [:index, :show, :create, :new]

    resources :cart_products, only: [:index, :create, :update]
    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
    delete 'cart_products/:id' => 'cart_products#destroy', as: 'destroy_cart_product'

    resource :customers, only: [:edit, :update]
    get 'customers/my_page' => 'customers#show', as: 'customer_show'
    get 'customers/quit_confirm' => 'customers#quit_confirm'
    patch 'customers/quit' => 'customers#quit'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    get '/' => 'homes#top', as: 'top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :show, :new, :create, :edit, :update]
    resources :orders, only: [:show, :update] do
    resources :order_details, only: [:update]
    end
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postcode,  presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  # ======= 会員ステータスが有効の場合TRUEを返す =======
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
      flash[:notice] = "会員情報を更新しました！"
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :is_deleted)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customer_show_path(current_customer.id)
    # super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_forailsr(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-8 col-xs-offset-1">
      <h5 class="d-inline-flex bg-light mt-5 mb-3"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h5>
    </div>
  </div>

  <%= form_with model: @customer, url: admin_customer_path ,method: :PATCH, local: true do |f| %>
  <div class="row">
    <div class="col-md-8">
      <table class="table table-borderless">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th style="width:60px"><%= f.label :氏名 %></th>
          <td class="d-flex">
            <%= f.text_field :last_name, class:"form-control mr-3" %>
            <%= f.text_field :first_name, class:"form-control" %>
          </td>
        </tr>
        <tr>
          <th><%= f.label :フリガナ %></th>
          <td class="d-flex">
            <%= f.text_field :last_name_kana, class:"form-control mr-3" %>
            <%= f.text_field :first_name_kana, class:"form-control" %>
          </td>
        </tr>
        <tr>
          <th><%= f.label :郵便番号 %></th>
          <td><%= f.text_field :postcode, class:"form-control" %></td>
        </tr>
        <tr>
          <th><%= f.label :住所 %></th>
          <td><%= f.text_field :address, class:"form-control" %></td>
        </tr>
        <tr>
          <th><%= f.label :電話番号 %></th>
          <td><%= f.text_field :phone_number, class:"form-control" %></td>
        </tr>
        <tr>
          <th><%= f.label :メールアドレス %></th>
          <td><%= f.text_field :email , class:"form-control"%></td>
        </tr>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <tr class="form-group form-inline d-flex flex-nowrap">
          <th class="form-group form-inline mr-5">会員ステータス</th>
          <td class="p-0 form-group form-inline ml-5">
          　<%= f.radio_button :is_deleted, :false %>
          　<%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
          　<%= f.radio_button :is_deleted, :true %>
          　<%= f.label :is_active, "退会", {value: :true, style: "display: inline-block;"} %>
          </td>
        </tr>
        <tr>
          <td>
          <%= f.submit "変更を保存", class: "btn btn-success" %>
          </td>
        </tr>
      </div>
    </div>
    </table>

<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <h3>会員一覧</h3>
    <table class="table">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == false %>
              <p class="active_color">
                有効
              </p>
              <% else %>
              <p class="inactive_color">
                退会
              </p>
              <% end %>
            </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-8 col-xs-offset-1">
      <h5 class="d-inline-flex bg-light my-4"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <table class="table table-borderless">
        <tr class="col-md-10">
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted == false %>
              <span class="active_color label label-primary">
                有効会員
              </span>
            <% else %>
              <span class="inactive_color label label-danger">
                退会済み
              </span>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 offset-md-2 text-center">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
    </div>
    <div class="col-md-4">
      <%= link_to "注文一覧を見る", admin_top_path, class: "btn btn-primary" %>
    </div>
  </div>

</div>