config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
    }

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'

    resources :orders, only: [:index, :show, :create, :new]

    resources :cart_products, only: [:index, :create, :update]
    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
    delete 'cart_products/:id' => 'cart_products#destroy', as: 'destroy_cart_product'

    resource :customers, only: [:edit, :update]
    get 'customers/my_page' => 'customers#show', as: 'customer_show'
    get 'customers/quit_confirm' => 'customers#quit_confirm'
    patch 'customers/quit' => 'customers#quit'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    get '/' => 'homes#top', as: 'top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :show, :new, :create, :edit, :update]
    resources :orders, only: [:show, :update] do
    resources :order_details, only: [:update]
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

   def order_detail
    self.postcode + self.destination + self.delivery_name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postcode,  presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  # ======= 会員ステータスが有効の場合TRUEを返す =======
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status: {入金待ち:0, 入金確認:1,  製作中:2, 発送準備中:3, 発送済み:4}

   def order_detail
    self.postcode + self.destination + self.delivery_name
   end

    def tax_included_price
     tax_rate = 1.08
     price * tax_rate
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  enum making_status: {制作不可:0, 製作待ち:1,  製作中:2, 製作完了:3}

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_details, dependent: :destroy

  attachment :image

  validates :name, presence: true
  validates :price, presence: true

  def is_active_to_string
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def tax_included_price
    tax_rate = 1.08
    price * tax_rate
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer

    @sub_total = 0
    @order.order_details.each do |order_detail|
    @sub_total += order_detail.product.tax_included_price.floor * order_detail.product_quantity
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order)

    if @order.order_status == "入金確認"

      @order.order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
  end

  def order_params
    params.require(:order).permit(:postcode, :total_price, :payment_method, :destination, :delivery_name, :order_status, :making_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

# ====== ログイン・ログアウト後の遷移先 ==========
  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_top_path
    else resource_or_scope == :customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      new_customer_session_path
    else resource_or_scope == :admin
      new_admin_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :email,
      :postcode,
      :address,
      :phone_number
      ])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 offset-md-1">
      <h5 class="d-inline-flex bg-light px-3 py-1 font-weight-bold mt-5 mb-4">注⽂履歴詳細</h5>
    </div>
  </div>

<div class="row">
   <div class="col-xs-9">
     <table class="table table-borderless">
         <thead>
            <tr><th>購入者</th><td><%= @customer.last_name + @customer.first_name %></td></tr>
            <tr><th>注文日</th><td><%= @order.created_at.to_s(:slash) %></td></tr>
            <tr><th>配送先</th><td>〒<%= @order.postcode %><%= @order.destination %><%= @order.delivery_name %></td></tr>
            <tr><th>支払方法</th><td><%= @order.payment_method %></td></tr>
            <tr>
             <th>注文ステータス</th>
              <td>
                <%= form_with(model: @order, url: admin_order_path, method: :patch, local: true) do |f| %>
                <%= f.select :order_status, Order.order_statuses_i18n.keys.map{|k| [I18n.t("enums.order.order_status.#{k}"), k]}, {} %>
                <%= f.submit '更新', class:"btn btn-sm btn-success" %>
                <% end %>
              </td>
              <td></td>
           </tr>
         </thead>
     </table>
  </div>
</div>

<div class="row">
   <div class="col-xs-8">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th class="text-left">商品名</th>
            <th class="text-left">単価(税込)</th>
            <th class="text-left">数量</th>
            <th class="text-left">小計</th>
            <th class="text-left">制作ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @order.order_details.each do |order_detail| %>
          <tr>
            <td>
              <p><%= order_detail.product.name %></p>
            </td>
            <td>
              <p><%= order_detail.product.tax_included_price.floor %></p>
            </td>
            <td>
              <p><%= order_detail.product_quantity %></p>
            </td>
            <td>
              <p><%= order_detail.product.tax_included_price.floor * order_detail.product_quantity %></p>
            </td>
              <td>
                  <%= form_with(model: order_detail, url: admin_order_order_detail_path(order_detail.id), method: :patch, local: true) do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, {} %>
                  <%= f.submit '更新', class:"btn btn-sm btn-success" %>
                  <% end %>
             </td>
          </tr>
       <% end %>
       </tbody>
      </table>
    </div>
    <div class="col-xs-3 offset-md-1">
      <table class="table table-borderless">
        <% @sum = 0 %>
         <thead>
            <tr><th>商品合計</th><td><%= @sub_total %></td></tr>
            <tr><th>配送料</th><td><%= 800 %></td></tr>
            <tr><th>請求⾦額合計</th><td><%= @sum = @sub_total + 800 %></td></tr>
         </thead>
       </table>
     </div>
  </div>


</div>