config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
    }

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'

    resources :orders, only: [:index, :show, :create, :new]

    resources :cart_products, only: [:index, :create, :update]
    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
    delete 'cart_products/:id' => 'cart_products#destroy', as: 'destroy_cart_product'

    resource :customers, only: [:edit, :update]
    get 'customers/my_page' => 'customers#show', as: 'customer_show'
    get 'customers/quit_confirm' => 'customers#quit_confirm'
    patch 'customers/quit' => 'customers#quit'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    get '/' => 'homes#top', as: 'top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :show, :new, :create, :edit, :update]
    resources :orders, only: [:show, :update] do
    resources :order_details, only: [:update]
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

   def order_detail
    self.postcode + self.destination + self.delivery_name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postcode,  presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  # ======= 会員ステータスが有効の場合TRUEを返す =======
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status: {入金待ち:0, 入金確認:1,  製作中:2, 発送準備中:3, 発送済み:4}

   def order_detail
    self.postcode + self.destination + self.delivery_name
   end

    def tax_included_price
     tax_rate = 1.08
     price * tax_rate
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  enum making_status: {制作不可:0, 製作待ち:1,  製作中:2, 製作完了:3}

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_details, dependent: :destroy

  attachment :image

  validates :name, presence: true
  validates :price, presence: true

  def is_active_to_string
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def tax_included_price
    tax_rate = 1.08
    price * tax_rate
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to admin_product_path(@product.id)

  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to admin_product_path(@product.id)
  end

  private

  def product_params
    params.require(:product).permit(:image, :name, :introduction, :price, :is_active, :genre_id, )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

# ====== ログイン・ログアウト後の遷移先 ==========
  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_top_path
    else resource_or_scope == :customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      new_customer_session_path
    else resource_or_scope == :admin
      new_admin_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :email,
      :postcode,
      :address,
      :phone_number
      ])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
  <!----------- 商品編集画面------------->

<div class="container">

  <div class="row">
    <div class="col-md-6 offset-md-2">
      <h5 class="d-inline-flex bg-light px-3 py-1 font-weight-bold mt-5">商品編集</h5>
    </div>
  </div>

   <%= form_with model: [:admin, @product], local: true do |f| %>
   <div class="row">
     <div class="col-md-8 offset-md-3 mt-4 pl-5">
       <div class="form-group form-inline pl-3">
         <p class="mr-4">商品画像</p>
         <div class="ml-5"><%= f.attachment_field :image %></div>
       </div>

       <div class="form-group form-inline">
       　<p class="mr-4 pr-3">商品名</p>
         <div class="ml-5"><%= f.text_field :name, placeholder: "商品名", size: "30", class: "form-control" %></div>
       </div>

       <div class="form-group form-inline">
       　<p class="mr-4">商品説明</p>
         <div class="ml-5"><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "30x5", class: "form-control" %></div>
       </div>

       <div class="form-group form-inline">
       　<p class="mr-4">ジャンル</p>
         <div class="ml-5"><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--", size: "30", class: "form-control" %></div>
       </div>

       <div class="form-group form-inline">
       　<p class="mr-4">税抜価格</p>
         <p class="ml-5"><%= f.text_field :price, placeholder: "1000", size: "30", class: "form-control" %> 円</p>
       </div>

       <div class="form-group form-inline">
       　<p class="mr-4">販売ステータス</p>
       　<%= f.radio_button :is_active, :true %>
       　<%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
       　<%= f.radio_button :is_active, :false %>
       　<%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
       </div>
     </div>
   </div>

  <div class="row">
    <div class="col-md-3 offset-md-6 mt-3">
      <%= f.submit '変更を保存', class:"btn btn-sm btn-success" %>
    </div>
  </div>
  <% end %>

</div>

app/views/admin/products/index.html.erb
  <!----------- 管理者：商品一覧画面------------->

<div class="container">

  <div class="row">
    <div class="col-md-6 offset-md-1">
      <h5 class="d-inline-flex bg-light px-3 py-1 font-weight-bold mt-5 mb-4">商品一覧</h5>
    </div>
    <div class="col-md-2 offset-md-3">
      <%= link_to "", new_admin_product_path, class:"fas fa-plus-circle fa-3x new_btn_color" %>
    </div>
  </div>

 <div class="row">
  <div class="col-md-11 pl-5">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th class="text-left">商品ID</th>
          <th class="text-left">商品名</th>
          <th class="text-left">税込価格</th>
          <th class="text-left">ジャンル</th>
          <th class="text-left">ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><u><%= link_to product.name, admin_product_path(product.id), class:"text-dark" %></u></td>
          <td><%= product.tax_included_price.floor %></td>
          <td><%= product.genre.name %></td>
          <% if product.is_active == true %>
            <td class="active_color"><%= product.is_active_to_string %></td>
          <% else %>
            <td class="inactive_color"><%= product.is_active_to_string %></td>
          <% end %>
        </tr>
      <% end %>
     </tbody>
    </table>
  </div>
 </div>

</div>

app/views/admin/products/new.html.erb
  <!----------- 商品新規登録画面------------->

<div class="container">

  <div class="row">
    <div class="col-md-6 offset-md-2">
      <h5 class="d-inline-flex bg-light px-3 py-1 font-weight-bold mt-5">商品新規登録</h5>
    </div>
  </div>

 <%= form_with model: [:admin, @product], local:true do |f| %>
 <div class="row">
  <div class="col-md-8 offset-md-3 mt-4 pl-5">
      <div class="form-group form-inline pl-3">
        <p class="mr-4">商品画像</p>
        <div class="ml-5"><%= f.attachment_field :image %></div>
      </div>

      <div class="form-group form-inline">
      　<p class="mr-4 pr-3">商品名</p>
        <div class="ml-5"><%= f.text_field :name, placeholder: "商品名", size: "30", class: "form-control" %></div>
      </div>

      <div class="form-group form-inline">
      　<p class="mr-4">商品説明</p>
        <div class="ml-5"><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "30x5", class: "form-control" %></div>
      </div>

      <div class="form-group form-inline">
      　<p class="mr-4">ジャンル</p>
        <div class="ml-5"><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--", size: "30", class: "form-control" %></div>
      </div>

      <div class="form-group form-inline">
      　<p class="mr-4">税抜価格</p>
        <p class="ml-5"><%= f.text_field :price, placeholder: "1000", size: "30", class: "form-control" %> 円</p>
      </div>

      <div class="form-group form-inline">
      　<p class="mr-4">販売ステータス</p>
      　<%= f.radio_button :is_active, :true %>
      　<%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
      　<%= f.radio_button :is_active, :false %>
      　<%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
      </div>
    </div>
   </div>

  <div class="row">
    <div class="col-md-3 offset-md-6 mt-3">
      <%= f.submit '新規登録', class:"btn btn-sm btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/products/show.html.erb
  <!----------- 管理者：商品詳細画面------------->
<div class="container ml-0">

  <div class="row">
    <div class="col-md-6 offset-md-2">
      <h5 class="d-inline-flex bg-light px-3 py-1 font-weight-bold mt-5 mb-2">商品詳細</h5>
    </div>
  </div>

  <div class="row mt-5 offset-md-2">
    <div class="col-md-3 text-center">
      <%= attachment_image_tag @product, :image, :fill, 200, 200, format: 'jpeg' %>
    </div>
    <div class="col-md-8 ml-5">
      <table class="table">
        <tbody>
          <tr>
            <td><p>商品名</p></td>
            <td><%= @product.name %></td>
          </tr>
          <tr>
            <td><p>商品説明</p></td>
            <td><%= @product.introduction %></td>
          </tr>
          <tr>
            <td><p>ジャンル</p></td>
            <td><%= Genre.find(@product.genre_id).name %></td>
          </tr>
          <tr>
            <td><p>税込価格</br>(税抜価格)</td>
            <td><p><%= @product.tax_included_price.floor %>（<%= @product.price %>）円</p></td>
          </tr>
          <tr>
            <td><p>販売ステータス</p></td>
            <% if @product.is_active == true %>
              <td class="active_color"><%= @product.is_active_to_string %></td>
            <% else %>
              <td class="inactive_color"><%= @product.is_active_to_string %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 mt-3 text-center offset-md-4">
      <%= link_to '編集', edit_admin_product_path(@product.id), class: 'btn btn-sm btn-success' %>
    </div>
  </div>
</div>