config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
    }

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resources :products, only: [:index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'

    resources :orders, only: [:index, :show, :create, :new]

    resources :cart_products, only: [:index, :create, :update]
    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
    delete 'cart_products/:id' => 'cart_products#destroy', as: 'destroy_cart_product'

    resource :customers, only: [:edit, :update]
    get 'customers/my_page' => 'customers#show', as: 'customer_show'
    get 'customers/quit_confirm' => 'customers#quit_confirm'
    patch 'customers/quit' => 'customers#quit'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    get '/' => 'homes#top', as: 'top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :show, :new, :create, :edit, :update]
    resources :orders, only: [:show, :update] do
    resources :order_details, only: [:update]
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

   def order_detail
    self.postcode + self.destination + self.delivery_name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postcode,  presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  # ======= 会員ステータスが有効の場合TRUEを返す =======
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status: {入金待ち:0, 入金確認:1,  製作中:2, 発送準備中:3, 発送済み:4}

   def order_detail
    self.postcode + self.destination + self.delivery_name
   end

    def tax_included_price
     tax_rate = 1.08
     price * tax_rate
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  enum making_status: {制作不可:0, 製作待ち:1,  製作中:2, 製作完了:3}

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_details, dependent: :destroy

  attachment :image

  validates :name, presence: true
  validates :price, presence: true

  def is_active_to_string
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def tax_included_price
    tax_rate = 1.08
    price * tax_rate
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

# ====== ログイン・ログアウト後の遷移先 ==========
  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_top_path
    else resource_or_scope == :customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      new_customer_session_path
    else resource_or_scope == :admin
      new_admin_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :email,
      :postcode,
      :address,
      :phone_number
      ])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <div class="container">
    <div class="small text-center text-muted pt-3">
      <div class="footer__logo">
        <%= link_to image_tag("naganocake_footerlogo.png"), root_path %>
      </div>
      <p class="text-light">Copyright © Nagano Cake. All Rights Reserved</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark ">
    <div class="container">
      <h1 class="navbar-brand logo">
        <%= link_to image_tag("naganocake_headerlogo.png"), root_path %>
      </h1>
      <ul class="navbar-nav">
        <% if customer_signed_in? %>

          <!--カスタマーがログインしている時 -->
          <li class="nav-item mr-5 pt-2">
            ようこそ、<span class="text-success mr-1"><%= current_customer.last_name %><%= current_customer.first_name %></span>さん！
          </li>
          <li class="nav-item"><%= link_to "マイページ", customer_show_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "商品一覧", products_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "カート", cart_products_path, class: 'nav-link ' %></li>
          <li class="nav-item ml-1"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link' %></li>

        <% elsif admin_signed_in? %>

          <!-- 管理者がログインしている時 -->
          <li class="nav-item"><%= link_to "商品一覧", admin_products_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "注文履歴一覧", admin_top_path , class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>

        <% else %>

          <!-- ログインしていない時 -->
          <li class="nav-item"><%= link_to "About", about_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "商品一覧", products_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "ログイン", new_customer_session_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/d64cb48cf6.js" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="container mt-2">
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>